# .streamlit/secrets.toml
SUPABASE_URL = "https://gfwiyknlvhgmiyyyybay.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmd2l5a25sdmhnbWl5eXl5YmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjU3OTQsImV4cCI6MjA2MzM0MTc5NH0.Gb1GhnFiLWeC9mJevfLnXsMZKGknNS_IlYTRFvm7Qw8"