# .streamlit/secrets.toml
SUPABASE_URL = "https://gfwiyknlvhgmiyyyybay.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmd2l5a25sdmhnbWl5eXl5YmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjU3OTQsImV4cCI6MjA2MzM0MTc5NH0.Gb1GhnFiLWeC9mJevfLnXsMZKGknNS_IlYTRFvm7Qw8"

# .streamlit/secrets.toml

[auth]
redirect_uri = "http://localhost:8503/oauth2callback" # e.g., "http://localhost:8501/oauth2callback" or "https://your-app-name.streamlit.app/oauth2callback"
cookie_secret = "4b8e3de46fbf1e1665b3a609fe343360a68279b6308c1151869c1d899b012d80" # Generate a long, random string
client_id = "273464548045-tppc6njbjnam8vs2c92nkttmqlafcfln.apps.googleusercontent.com" # From Google Cloud Console
client_secret = "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" # From Google Cloud Console
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"